// 四张地图的主题配置。视觉元素参考 QQ飞车官方地图原画：
// 11城（塔桥、SPEED 飞艇、吉祥物气球、蓝色加速箭头）、情迷爱琴海（白墙蓝顶、石板路、三角梅）、
// 法老金字塔（紫白格起点、有翼狮身像、太阳圆盘门楼）、雪地大冒险（雪松、奖杯、热气球、看台横幅）
export const MAPS = [
  {
    id: 'city',
    name: '11城',
    en: 'CITY 11',
    tag: '经典竞速 · 11 个弯道',
    desc: '跨河塔桥、摩天楼群与蓝色霓虹加速带，节奏感极强的都市赛道。',
    layout: 'city',
    sky: { top: '#2f7fe0', horizon: '#cfeaff', bottom: '#8fb8d8', sun: [-0.45, 0.62, -0.55], sunColor: '#fff4dc', sunI: 2.6 },
    hemi: ['#d6ecff', '#6f8a5a', 1.1],
    fog: ['#cfe6fb', 380, 2300],
    ground: 'grass',
    groundTint: '#ffffff',
    water: { color: '#1f7fd1', deep: '#0b3f7a', y: -1.6 },
    track: {
      road: 'asphalt', wall: 'city', curbA: '#e53935', curbB: '#ffffff', deckColor: 0xc7c3d6,
      checkerA: '#101010', checkerB: '#ffffff', boostColor: '#27c7ff',
      boostPads: [{ at: [-120, -151] }, { at: [205, -8] }, { at: [-262, 8], lat: -4 }, { at: [-262, 8], lat: 4 }],
      shoulder: { width: 7, tex: 'plaza' },
    },
    isBridge: (x, z, y) => Math.abs(z) < 80 && y > 1.5,
    bgm: 0,
  },
  {
    id: 'aegean',
    name: '情迷爱琴海',
    en: 'AEGEAN SEA',
    tag: '山城爬坡 · 连续发卡弯',
    desc: '白墙蓝顶的海岛小镇，石板路盘山而上，发卡弯考验连续漂移。',
    layout: 'aegean',
    sky: { top: '#3a8ee6', horizon: '#e4f3ff', bottom: '#9cc6e6', sun: [0.5, 0.55, -0.45], sunColor: '#fff1d6', sunI: 2.7 },
    hemi: ['#e8f4ff', '#a39a7a', 1.15],
    fog: ['#dcefff', 420, 2400],
    ground: 'aegean',
    groundTint: '#ffffff',
    water: { color: '#1a8fd8', deep: '#07477f', y: -1.0 },
    track: {
      road: 'flagstone', wall: 'aegean', curbA: '#2f7fd8', curbB: '#ffffff', deckColor: 0xe9e4d8,
      checkerA: '#1d4f9e', checkerB: '#ffffff', boostColor: '#ffd23a',
      boostPads: [{ at: [-60, -178] }, { at: [120, 115] }],
      tunnels: [{ from: [-296, 128], to: [-340, 10] }],
      shoulder: { width: 5, tex: 'plaza' },
      tunnelOuter: 0xf2eee6,
    },
    bgm: 1,
  },
  {
    id: 'egypt',
    name: '法老金字塔',
    en: 'PHARAOH',
    tag: '沙漠飞跃 · 神殿隧道',
    desc: '穿过法老神殿，冲上沙丘跳台飞跃，落地瞬间来一记落地喷！',
    layout: 'egypt',
    sky: { top: '#3b86d8', horizon: '#fbe7c4', bottom: '#e9c99a', sun: [0.35, 0.5, 0.6], sunColor: '#fff0cf', sunI: 3.0 },
    hemi: ['#fff1d8', '#c49a5a', 1.05],
    fog: ['#f3dfbd', 420, 2500],
    ground: 'sand',
    groundTint: '#ffffff',
    water: { color: '#23a3b8', deep: '#0d5a6a', y: -0.6, local: true },
    track: {
      road: 'sandstone', wall: 'egypt', curbA: '#5b3f9e', curbB: '#f3e3b5', deckColor: 0xd9b77a,
      checkerA: '#5b3f9e', checkerB: '#ffffff', boostColor: '#ff9a1f',
      boostPads: [{ at: [2, -60] }, { at: [300, 20] }],
      tunnels: [{ from: [0, -250], to: [0, -150] }],
      tunnelOuter: 0xd6b274,
    },
    bgm: 2,
  },
  {
    id: 'snow',
    name: '雪地大冒险',
    en: 'SNOW ADVENTURE',
    tag: '8 字立交 · 冰雪隧道',
    desc: '雪松林与冰雪隧道，8 字形立交桥上下穿梭，终点看台为你欢呼。',
    layout: 'snow',
    sky: { top: '#3f86d6', horizon: '#e2f0ff', bottom: '#c9ddf2', sun: [-0.3, 0.45, 0.7], sunColor: '#ffffff', sunI: 2.4 },
    hemi: ['#eef6ff', '#9fb4cc', 1.25],
    fog: ['#e3eefb', 350, 2200],
    ground: 'snow',
    groundTint: '#ffffff',
    track: {
      road: 'plate', wall: 'snow', curbA: '#c62828', curbB: '#ffffff', deckColor: 0x9fb0c8,
      checkerA: '#101010', checkerB: '#ffffff', boostColor: '#39c5ff',
      boostPads: [{ at: [-60, -200] }, { at: [-20, 120] }],
      tunnels: [{ from: [-110, -52], to: [-235, -40] }],
      tunnelOuter: 0xdfeaf6,
      roadMetal: 0.35, roadRough: 0.55,
    },
    isBridge: (x, z, y) => y > 5.5,
    snowfall: true,
    bgm: 3,
  },
];

export const MODES = [
  { id: 'speed', name: '竞速模式', desc: '漂移集气、小喷、双喷，纯靠车技' },
  { id: 'item', name: '道具模式', desc: '导弹、香蕉皮、天使、磁铁、氮气' },
];
